- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
   - name: Actualizar sistema
     become: yes
     command: apt-get update
   - name: Instalar essential
     become: yes
     command: apt-get install -y build-essential
   - name: Instalar Git
     become: yes
     command: apt-get install -y git
   - name: Instalar pip
     become: yes
     command: apt-get install -y python3-pip
   - name: Actualizar pip
     become: yes
     command: pip3 install --upgrade pip
   - name: Clonar GitHub
     become: yes
     git: repo=https://github.com/Maverick94/IV_Proyecto/  dest=home/vagrant/IV_Proyecto clone=yes force=yes
<<<<<<< HEAD
   # - name: Instalar requirements
   #   become: yes
   #   command: pip install -r /home/vagrant/IV_Proyecto/requirements.txt
=======
  #  - name: Entrar en el directorio
  #    become: yes
  #    command: cd /home/vagrant/IV_Proyecto
  #  - name: Instalar requirements
  #    become: yes
  #    command: pip3 install -r requirements.txt
>>>>>>> 2eb1a87b2e170dbfcd654682f4bb1abc5a0215bd
