#Para que no haya conflicto con gh-pages
branches:
  only:
  - master

language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements.txt
#Pasa los tests a la primera biblioteca creada
script: make test
